version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: medicaai_db
    environment:
      POSTGRES_DB:       medicaai_dev
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: MedicaAI.API/Dockerfile
    container_name: medicaai_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT:          Development
      ASPNETCORE_URLS:                 http://+:8080
      ConnectionStrings__Default:      Host=postgres;Port=5432;Database=medicaai_dev;Username=postgres;Password=postgres
      Jwt__Key:                        MedicaAI_Super_Secret_Key_Min32Chars_CHANGE_IN_PROD!!
      Jwt__Issuer:                     http://localhost:8080
      Jwt__ExpiresInMinutes:           "60"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
